version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    links:
      - "postgres:lol"

volumes:
    pgadmin:
    postgres: